/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChannelInfo = IDL.Record({
  'bio' : IDL.Text,
  'channelUrl' : IDL.Text,
  'channelName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBio' : IDL.Func([], [IDL.Text], ['query']),
  'getChannelInfo' : IDL.Func([], [ChannelInfo], ['query']),
  'getChannelName' : IDL.Func([], [IDL.Text], ['query']),
  'getChannelUrl' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChannelInfo = IDL.Record({
    'bio' : IDL.Text,
    'channelUrl' : IDL.Text,
    'channelName' : IDL.Text,
  });
  
  return IDL.Service({
    'getBio' : IDL.Func([], [IDL.Text], ['query']),
    'getChannelInfo' : IDL.Func([], [ChannelInfo], ['query']),
    'getChannelName' : IDL.Func([], [IDL.Text], ['query']),
    'getChannelUrl' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };